language: android
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-19

before_script:
      - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
      - emulator -avd test -no-skin -no-audio -no-window &
      - adb wait-for-device
      - android-wait-for-emulator
      - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest

notifications:
  slack:
    secure: IaLAj/gN+zLh5dTP7B+TWZiAqcqVyh5Apbb/jnpv1WcWFKOCFvymysbA0i9U8YYi3UWVY4MxlNh0MZM9rtDYtxQfA4JinROiEhagTyWu7QdlfV4NsL1Rw6QiPKfEY4NAltB91nBzQWTawIz2uji4Dq5riBEiuLZ/rnDZHAU6STnQk30xUa2fRlmC2mxBpSUqCbXjPz/nt7QD+bR03TIIcuSd5ICkwNDDAnrpDBzODdC9gBNicRqYc0Yv0cTZguSID2Hr4jL9Ipvg5tfZVgNpYaGAA7RiW4V7gU7wIgAerPDhsIoJmwtrnz+HMnOuVeX7pud21vxbkZWMqt9yDtk+UFwx+5iCqfaX+1BQZo4tTUQkZ/QEJZmfjl10JJqdVzJ1LvZJyf0LV3cl1yF8++aZWVb2SElNjg7BzozxIFInT6Wm7VtyLOsTCxXNBE39ZlyqLUd/+UNhmiK8E0UNTAbNcc0cbHZAvebFTxHgXZjSsJf34w+yunDCw03mBgr/ba+g+rKddeup2Gngz/0dZMKopoXBiiayIhXM8mUOtcdjRBpAz1cNpY+sgcDqGIILMamtGhnohvzTNS3r3p3YY2LMt4oxTfLMfZOkKopfhk3CLpGZuIISBCGNeg6fLtWJlBYZ+bQvf6XSlTZbFlKqlUxXggpGo3jL8EhflJ/Zyj9+SkE=
